[/]
change-wallpaper=true
change-wallpaper-directory-path='/home/luka/Videos/Hidamari/Monochrome Cyclee'
change-wallpaper-interval=300
change-wallpaper-mode=2
clock-font-size=70
clock-offset-x=56
clock-offset-y=24
clock-opacity=100
clock-position=3
clock-show-seconds=false
content-fit=2
debug-mode=true
enable-graphics-offload=true
low-battery-threshold=50
mute=false
show-clock=false
show-panel-menu=true
video-path='/home/luka/Videos/Hidamari/Monochrome Cyclee/dark-samurai-where-winds-meet-moewalls-com.mp4'
volume=52
