[/]
change-wallpaper=true
change-wallpaper-directory-path='/home/luka/Videos/Hidamari/JJK_Cycle'
change-wallpaper-interval=60
change-wallpaper-mode=2
clock-font-size=70
clock-offset-x=56
clock-offset-y=24
clock-opacity=100
clock-position=3
clock-show-seconds=false
debug-mode=true
low-battery-threshold=50
mute=false
show-clock=false
show-panel-menu=true
video-path='/home/luka/Videos/Hidamari/JJK_Cycle/yuta-jjk.3840x2160.mp4'
volume=52
